# Generated by Django 3.2 on 2021-04-09 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import serpis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keluhan', models.TextField()),
                ('penanganan', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(choices=[('1', 'Tertunda'), ('2', 'Dikerjakan'), ('3', 'Selesai')], default='1', max_length=1)),
                ('pelanggan', models.CharField(max_length=125)),
                ('alamat', models.TextField()),
                ('telp', models.CharField(max_length=30)),
                ('tgl_masuk', models.DateField()),
                ('tgl_keluar', models.DateField()),
                ('biaya_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rincian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ket', models.CharField(max_length=125)),
                ('biaya', models.IntegerField(default=0)),
                ('orderan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rincian_orderan', to='serpis.orderan')),
            ],
        ),
        migrations.CreateModel(
            name='Orang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendapatan', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orang', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gambar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to=serpis.models.foto_orderan)),
                ('orderan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gambar_orderan', to='serpis.orderan')),
            ],
        ),
    ]
