# Generated by Django 3.2 on 2021-04-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serpis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderan',
            name='tgl_keluar',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderan',
            name='tgl_masuk',
            field=models.DateField(auto_now_add=True),
        ),
    ]
